#!/bin/bash

set -e

[ -z "$1" ] && exit

git clone git@github.com:ocawesome101/$1

rm -rf $1/.git

[ -z "$2" ] && gh repo delete ocawesome101/$1

echo "$1" >> chronological_order.txt

git add .; git commit
