#!/bin/bash
#
# Create UEFI-bootable Windows 8.1 or 10 media from Linux
# mkwin <ISO> <DEVICE>
#
# DEVICE must be formatted with partition 1 as 100MB of FAT32, and partition 2 of at
# least 5GB of NTFS. It must have a GPT partition table as well.

if ! [ "$#" = 2 ]; then
 echo "Usage: $0 <iso> /dev/sdX"
 exit 1
fi

if ! [ "$USER" = "root" ]; then
 echo "This script must be run as root"
 exit 1
fi

iso="$1"
device="$2"

grubcfg="
menuentry 'Start Windows installation (UEFI)' {
	insmod ntfs
	set root='hd0, gpt2'
	chainloader /efi/boot/bootx64.efi
	boot
}
"

mkdirs() {
 echo "-> Setting up directories"
 mkdir -p /mnt/win /mnt/boot /mnt/usb
}

mountdevices() {
 echo "-> Mounting devices"
 mount "$iso" /mnt/win
 mount "$device"1 /mnt/boot
 mount "$device"2 /mnt/usb
}

mkgrub() {
 echo "-> Installing GRUB"
 grub-install --target=x86_64-efi --boot-directory=/mnt/boot/boot --efi-directory=/mnt/boot "$device"
}

writecfg() {
 echo "-> Generating /mnt/boot/boot/grub/grub.cfg"
 echo "$grubcfg" > /mnt/boot/boot/grub/grub.cfg
}

cpfiles() {
 echo "-> Copying files. This may take some time..."
 cp -r /mnt/win/* /mnt/usb/
}

unmount() {
 echo "-> Unmounting devices"
 umount /mnt/*
}

mkdirs
mountdevices
mkgrub
writecfg
cpfiles
unmount
echo "-> Done."
