modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="morpicks"
version="1.2.0"
displayName="morpicks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ocawesome101, MCreator"

[[dependencies.morpicks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



